@startmindmap
'https://plantuml.com/mindmap-diagram

* java覆盖率工具
** 字节码分析模块
*** 类分析子模块
*** 方法分析子模块
** 输出分析模块
** 外部依赖模块
** 优化模块
*** 算法子模块
*** 数据结构子模块
** 存储模块
** 可视化模块
*** xml处理子模块
*** 图处理子模块
*** 报告生成子模块
** 工具模块
** api模块

@endmindmap
